POST http://localhost:3333/videos
Content-type: application/json 
// metadados são configurações enviadas no cabeçalho da requisição

// Ao fazer uma requisição do front para o back-end, é necessário informar ao back-end
// o formato dos dados que estão sendo enviados.

{
  "title": "Vídeo node",
  "description": "Esse é o primeiro vídeo",
  "duration": 180
}

###

GET http://localhost:3333/videos?search=node

###

PUT http://localhost:3333/videos/e2ab9549-97c0-4b4e-8459-361838306d6f
Content-type: application/json

{
  "title": "Vídeo 02",
  "description": "Esse é o primeiro vídeo",
  "duration": 180
}

###

DELETE http://localhost:3333/videos/c8161916-f0c1-49e1-a0a6-af71de36fbef