POST http://localhost:3333/videos
Content-type: application/json 
// metadados são configurações enviadas no cabeçalho da requisição

// Ao fazer uma requisição do front para o back-end, é necessário informar ao back-end
// o formato dos dados que estão sendo enviados.

{
  "title": "Vídeo node",
  "description": "Esse é o primeiro vídeo",
  "duration": 180
}

###

GET http://localhost:3333/videos?search=node

###

PUT http://localhost:3333/videos/0678e50e-4d1b-4267-924e-16f728913d68
Content-type: application/json

{
  "title": "Vídeo 02",
  "description": "Esse é o primeiro vídeo",
  "duration": 180
}

###

DELETE http://localhost:3333/videos/0678e50e-4d1b-4267-924e-16f728913d68